easy_admin:
    site_name: Administratoriaus panelė
    design:
        assets:
            css:
                - 'build/app.css'
        brand_color: '#000'
    list:
        actions: ['show']
    entities:
        # List the entity class name you want to manage
        Podcast:
            class: App\Entity\Podcast
            label: Podkastai
            list:
                title: Visi podkastai
                fields:
                    - id
                    - { property: title, label: "Antraštė" }
                    - { property: description, label: "Aprašymas" }
                    - { property: image, label: "Paveikslėlis", type: image, sortable: false }
                    - { property: publishedAt, label: "Publikuotas", type: date }
                    - { property: createdAt, label: "Išasugotas", type: date }
            edit:
                fields:
                    - { property: image, label: "Paveiksėlis"}
#            search:
#                title: Rasti rezultatai
        Source:
            class: App\Entity\Source
            label: Šaltiniai
            list:
                title: Visi šaltiniai
                fields:
                    - id
                    - { property: name, label: 'Pavadinimas' }
                    - { property: url, label: "Svetainė", type: url }
                    - { property: sourceType, label: "Tipas" }
            form:
                fields:
                    - { property: name, label: 'Pavadinimas' }
                    - { property: url, label: "Svetainė", type: url }
                    - { property: mainElementSelector, label: "Pag. selektorius" }
                    - { property: imageSelector, label: "Img selektorius"}
                    - { property: titleSelector, label: "Antraštės selektorius" }
                    - { property: descriptionSelector, label: "Aprašymo selektorius" }
                    - { property: audioSelector, label: "Audio failo selektorius" }
                    - { property: audioSourceAttribute, label: "Audio elemento atributas"}
                    - { property: publicationDateSelector, label: "Datos selektorius" }
                    - { property: imageSourceAttribute, label: "Img atributas" }
                    -
                        property: sourceType
                        label: "Tipas"
                        type: choice
                        type_options:
                            choices: {'Audio': 'Audio', 'Youtube': 'Youtube'}
                            placeholder: 'Pasirinkite tipą'
        User:
            class: App\Entity\User
            label: Vartotojai
            list:
                fields:
                    - { property: username, label: 'El paštas' }
                    - { property: fullName, label: 'Pilnas Vardas' }
                    - { property: createdAt, label: 'Registracijos data', type: date }
                    - { property: isConfirmed, label: 'Aktyvuotas vartotojas' }
            show:
                fields:
                    - { property: username, label: 'El paštas' }
                    - { property: fullName, label: 'Pilnas Vardas' }
            edit:
                fields:
                    - { property: username, label: 'El paštas' }
                    - { property: password, label: 'Slaptažodis', type: password, value: password }
                    - { property: fullName, label: 'Pilnas Vardas' }
        Tag:
            class: App\Entity\Tag
            label: Raktažodžiai
        Subscriber:
            class: App\Entity\Subscriber
            label: Prenumeratoriai
            list:
                fields:
                    - id
                    - { property: email, type: email, label: "El. paštas"}
                    - { property: isConfirmed, type: boolean, label: "Aktyvuotas" }
                    - { property: createdAt, label: Sukurtas, type: date }

        Comment:
            class: App\Entity\Comment
            label: Komentarai
            list:
                fields:
                    - id
                    - { property: body, label: 'Komentaras', type: text }
                    - { property: user, label: 'Autorius' }
                    - { property: podcast, label: 'Podkastas', type: string }
