easy_admin:
    user:
        name_property_path: 'fullName'

    design:
        menu:
            - { label: 'Eiti į vartotojo paskyrą', route: 'user_panel', icon: 'hand-point-left' }
            - Podcast
            - Source
            - User
            - Tag
            - Subscriber
            - Comment

    site_name: Administratoriaus paskyra

    list:
        actions:
        - { name: 'new', label: Pridėti, icon: 'plus-circle', title: 'Pridėti' }
        - { name: 'show', label: false, icon: 'eye', title: 'Rodyti' }
        - { name: 'edit', label: false, icon: 'edit', title: 'Redaguoti' }
        - { name: 'delete',  label: false, icon: 'trash', title: 'Ištrinti' }
        - { name: 'search', label: 'Ieškoti' }

    show:
        actions:
        - { name: 'delete',  label: false, icon: 'trash', title: 'Ištrinti' }
        - { name: 'edit', label: false, icon: 'edit', title: 'Redaguoti' }
    edit:
        actions:
        - { name: 'delete',  label: 'Ištrinti' }

    entities:
        # List the entity class name you want to manage
        Podcast:
            class: App\Entity\Podcast
            label: Podkastai
            list:
                title: Visi podkastai
                fields:
                    - id
                    - { property: title, label: "Antraštė" }
                    - { property: description, label: "Aprašymas" }
                    - { property: image, label: "Paveikslėlis", type: image, sortable: false }
                    - { property: likesByUser, label: "Pamėgtas", sortable: true }
                    - { property: publishedAt, label: "Publikuotas", type: date }
                    - { property: createdAt, label: "Išasugotas", type: date }
            edit:
                fields:
                    - { property: title, label: "Antraštė" }
                    - { property: description, label: "Aprašymas" }
            show:
                fields:
                    - { property: title, label: "Antraštė" }
                    - { property: description, label: "Aprašymas" }
            search:
                title: Rasti rezultatai
            disabled_actions: ['new']
        Source:
            class: App\Entity\Source
            label: Šaltiniai
            list:
                title: Visi šaltiniai
                fields:
                    - id
                    - { property: name, label: 'Pavadinimas' }
                    - { property: url, label: "Svetainė", type: url }
                    - { property: sourceType, label: "Tipas" }
            form:
                fields:
                    - { property: name, label: 'Pavadinimas' }
                    - { property: url, label: "Svetainė", type: url }
                    - { property: mainElementSelector, label: "Pag. selektorius" }
                    - { property: imageSelector, label: "Img selektorius"}
                    - { property: titleSelector, label: "Antraštės selektorius" }
                    - { property: descriptionSelector, label: "Aprašymo selektorius" }
                    - { property: audioSelector, label: "Audio failo selektorius" }
                    - { property: audioSourceAttribute, label: "Audio elemento atributas"}
                    - { property: publicationDateSelector, label: "Datos selektorius" }
                    - { property: imageSourceAttribute, label: "Img atributas" }
                    -
                        property: sourceType
                        label: "Tipas"
                        type: choice
                        type_options:
                            choices: {'Audio': 'Audio', 'Youtube': 'Youtube'}
                            placeholder: 'Pasirinkite tipą'
            disabled_actions: ['show']
        User:
            class: App\Entity\User
            label: Vartotojai
            list:
                fields:
                    - { property: username, label: 'El paštas' }
                    - { property: fullName, label: 'Pilnas Vardas' }
                    - { property: createdAt, label: 'Registracijos data', type: date }
                    - { property: isConfirmed, label: 'Aktyvuotas vartotojas', type: toggle }
                    - { property: roles, label: 'Rolės', template: 'front/pages/users/_roles.html.twig'}
            show:
                fields:
                    - { property: username, label: 'El paštas' }
                    - { property: fullName, label: 'Pilnas Vardas' }
                    - { property: createdAt, label: 'Registracijos data', type: date }
                    - { property: isConfirmed, label: 'Aktyvuotas vartotojas', type: toggle }
                actions: ['-delete']
            disabled_actions: ['edit', 'new']
        Tag:
            class: App\Entity\Tag
            label: Raktažodžiai
            edit:
                fields:
                    - { property: tag, label: 'Raktažodis' }
                    - { property: slug, label: 'Naršyklės url' }
        Subscriber:
            class: App\Entity\Subscriber
            label: Prenumeratoriai
            list:
                fields:
                    - id
                    - { property: email, type: email, label: "El. paštas"}
                    - { property: isConfirmed, type: toggle, label: "Aktyvuotas" }
                    - { property: createdAt, label: Sukurtas, type: date }
            disabled_actions: ['new']

        Comment:
            class: App\Entity\Comment
            label: Komentarai
            list:
                fields:
                    - id
                    - { property: body, label: 'Komentaras', type: text }
                    - { property: user, label: 'Autorius' }
                    - { property: podcast, label: 'Podkastas', type: string }
            show:
                fields:
                    - id
                    - { property: body, label: 'Komentaras', type: text }
                    - { property: user, label: 'Autorius' }
                    - { property: podcast, label: 'Podkastas', type: string }
            disabled_actions: ['edit', 'new']
